# Generated by Django 3.2.8 on 2021-10-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=50)),
                ('introduction', models.TextField()),
                ('img_url', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
