# Generated by Django 3.2.8 on 2021-10-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.FloatField(default=9.9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='img_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
