# Generated by Django 3.2.8 on 2021-10-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0004_student_stuinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuinfo',
            name='sid',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StuInfo',
        ),
    ]
