# Generated by Django 3.2.8 on 2021-10-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.CharField(default='/static/myadmin/assets/img/user03.png', max_length=100),
        ),
    ]
