# Generated by Django 3.2.8 on 2021-10-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_booktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tuijian', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('num', models.IntegerField()),
                ('ISBN', models.CharField(max_length=100)),
                ('context', models.TextField()),
                ('typeid', models.ManyToManyField(to='myadmin.BookType')),
            ],
        ),
        migrations.CreateModel(
            name='BookImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='uploads')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.books')),
            ],
        ),
    ]
