# Generated by Django 3.2.8 on 2021-10-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_bookimgs_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimgs',
            name='img_url',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
