# Generated by Django 3.2.8 on 2021-10-31 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=50)),
                ('totalprice', models.FloatField()),
                ('status', models.IntegerField(default=0)),
                ('ordertime', models.DateTimeField(auto_now_add=True)),
                ('paytime', models.DateTimeField(null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.users')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('price', models.FloatField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.books')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.order')),
            ],
        ),
    ]
