# Generated by Django 3.2.8 on 2021-10-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
